### ISSUE TITLE
Some constructors take `rdf_type` as first argument, breaking backward compatibility

### ISSUE THREAD

**Issue by tcmitchell** [llotneb/SBOL#113]
#57 boils down to a constructor whose arguments are not backward compatible. `Collection` takes `rdf_type` as its first argument, but in pySBOL the Collection constructor takes uri as the first argument _when called with two arguments_. This breaks things because rdf_type is used to store the collection on the the parent object. Having the wrong rdf_type makes the collection irretrievable.

Some possible solutions:

* We could stop letting the user change the rdf_type of a Collection. That doesn't feel like something that should be allowed. Too much depends on having the right rdf_type.
* We could get clever and figure out when the user is invoking with two arguments or three using variable argument lists. That will suck for documentation and source diving because it will make the module harder to understand.
* I'm sure there are other approaches too.

**Comment by bbartley** [comment]
It is important to be able to override RDF types. However, I think we should find a way that doesn't require passing the RDF type as the first argument to the constructor.  In libSBOL, the RDF type was an optional argument, but as noted above, this doesn't really translate well into a Python constructor pattern.

The reason that libSBOL allows you to override RDF types is related to extension classes. For example if I subclass `Interaction`, then obviously I don't want to serialize it into XML as such. That means I have to change the RDF triple:

    homespace:my_object rdf:type sbol:Interaction

to:

    homespace:my_object rdf_type sbol:InteractionSubclass

Hence, you are allowed to override the RDF type of an object.  In c++ it made sense to perform this override by directly passing the derived RDF type directly through a constructor.  Here we might have to find another convention, although I don't currently don't know what is best (perhaps using a keyword argument?).  The tradeoff is that Extension classes won't be perfectly backward-compatible.

**Comment by tcmitchell** [comment]
I propose that we use new [Python 3 syntax to force certain arguments to be keyword arguments](https://www.python.org/dev/peps/pep-3102/).

The new Collection constructor might look something like this:

```python
def __init__(self, uri=URIRef("example"), version=VERSION_STRING,
             *, type_uri=SBOL_COLLECTION)
```

This allows the `uri` and `version` arguments to be positional or keyword, and requires that
the `type_uri` argument be a keyword argument. That should be backward compatible with the most common use cases while still allowing the extension use case.

**Comment by bbartley** [comment]
I like the pattern of always making the `type_uri` the last argument.  But what's the reason for making `type_uri`  keyword only?  I guess it can prevent accidentally overwriting the rdf type.

**Comment by tcmitchell** [comment]
> I guess it can prevent accidentally overwriting the rdf type.

And accidentally overwriting the rdf_type has significant ramifications. Regardless of which method is used to add an SBOL Object to a Document, at its heart the rdf_type is what is actually used. Changing the rdf_type accidentally is the difference between finding the object again, and having the object go mysteriously missing.

Should the various Document `addXxx` methods (`addModuleDefinition`, `addCollection`, `addSequence`, etc.) check the rdf_type of the object and either error or warn if the object does not have the correct rdf_type? This would be in addition to the proposed change to always make the `type_uri` a keyword argument.
