### ISSUE TITLE
SYNBICT: `setPropertyValue` not implemented

### ISSUE THREAD

**Issue by bbartley** [llotneb/SBOL#125]
Running `python3 sequences_to_features.py -n http://synbict.org -t ../test/genetic_nand.xml -f ../test/cello_library.xml` raises:
```
Traceback (most recent call last):
  File "sequences_to_features.py", line 845, in <module>
    main()
  File "sequences_to_features.py", line 807, in main
    annotated_identities = feature_annotater.annotate(target_library, int(args.min_target_length))
  File "sequences_to_features.py", line 418, in annotate
    True, min_target_length)
  File "sequences_to_features.py", line 269, in copy_component_definition
    definition_copy.setPropertyValue('http://wiki.synbiohub.org/wiki/Terms/synbiohub#ownedBy', '')
  File "/Users/bbartley/Dev/git/sd2/SYNBICT_venv/lib/python3.7/site-packages/sbol-2.3.3b0-py3.7.egg/sbol/object.py", line 292, in setPropertyValue
    raise NotImplementedError("Not yet implemented")
```

**Comment by tcmitchell** [comment]
This method has recently been changed in [pysbol](https://github.com/SynBioDex/libSBOL/pull/220). It used to raise a LookupError if the property did not exist. Now it sets that property. Mimic the latest behavior.

This method was [deprecated](https://github.com/SynBioDex/libSBOL/pull/220/commits/944105e68e0dbd8578b4e6a12e6ee40e52bef80e#diff-5dba1a06c7140503773c9501db5e3530R146) in the same pull request. We should probably deprecate it in this library as well.

**Comment by tcmitchell** [comment]
`setPropertyValue` can have odd or unexpected behavior that should be mimicked. It only sets the first element in an underlying list. For example, note the final value of the ModuleDefinition's roles property:

```python
>>> import sbol
>>> md = sbol.ModuleDefinition('md')
>>> md.roles = [sbol.SBO_PRODUCT, sbol.SBO_LIGAND]
>>> md.roles
['http://identifiers.org/biomodels.sbo/SBO:0000011', 'http://identifiers.org/biomodels.sbo/SBO:0000280']
>>> md.setPropertyValue(sbol.SBOL_ROLES, '')
>>> md.roles
['', 'http://identifiers.org/biomodels.sbo/SBO:0000280']
>>> 
```

**Comment by tcmitchell** [comment]
The C++ code that underlies pysbol defaults to the value being a Literal, not a URIRef. So if setPropertyValue gets a string that is neither a Literal nor a URIRef, convert it to a Literal.
