### ISSUE TITLE
Cannot create locations

### ISSUE THREAD

**Issue by bbartley** [llotneb/SBOL#128]
Cannot create specialized subclasses of `Location`, e.g. `Range`
```
>>> sa.locations.createRange('r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'OwnedObject' object has no attribute 'createRange'
```

**Comment by tcmitchell** [comment]
Here's a complete example from SWIG pySBOL:

```
>>> import sbol
>>> sa = sbol.SequenceAnnotation('sa1')
>>> sa.identity
'http://examples.org/SequenceAnnotation/sa1/1'
>>> sa.locations.createRange('r')
Range
```

But here's another example from SWIG pySBOL that strikes me as a bug:

```
>>> import sbol
>>> md = sbol.ModuleDefinition('md1')
>>> r2 = md.modules.createRange('r2')
>>> type(r2)
<class 'sbol.libsbol.Range'>
>>> type(md.modules[0])
<class 'sbol.libsbol.Module'>
>>> r2.identity
'http://examples.org/ModuleDefinition/md1/r2/1'
>>> md.modules[0].identity
'http://examples.org/ModuleDefinition/md1/r2/1'
>>> r2.identity in md.modules
True
>>> x = md.modules[r2.identity]
>>> x
Module
>>> r2
Range
>>> x.identity
'http://examples.org/ModuleDefinition/md1/r2/1'
>>> r2.identity
'http://examples.org/ModuleDefinition/md1/r2/1'
```

That looks like we created a Range, and we actually did, but what really got stored in the ModuleDefinition's modules is a Module. And that Module has the same URI as the Range that got created. 

I think maybe what we want is a subclass of OwnedObject, like OwnedLocation, that has the various speciality methods like createRange. That would allow those methods in the right place, and only the right place.

**Comment by tcmitchell** [comment]
What I'd _really_ like to see is a more intuitive style, without the `create` methods. I find the semantics of the `create` methods counterintuitive. I would expect `createRange` to be a factory method, and only a factory method, with no side effects. And I'd like to see more use of constructors and assignment as is native to Python.

```
>>> import sbol
>>> sa = sbol.SequenceAnnotation('sa1')
>>> sa.identity
'http://examples.org/SequenceAnnotation/sa1/1'
>>> sa.locations = [Range('r1', rstart, rend), Cut('c1', cstart, cend), ...]
>>>
```

That, to me, seems far clearer than the way the `create` methods construct objects and append them to the collection.
