### ISSUE TITLE
Adding values to list properties follows a funny pattern

### ISSUE THREAD

**Issue by bbartley** [llotneb/SBOL#129]
Currently the following pattern allows the user to append new values to a list, but this behavior is probably not intuitive to most users, and is not reverse-compatible with SWIG pySBOL.
```
>>> cd = ComponentDefinition('cd')
>>> cd.roles = 'foo1'
>>> cd.roles
[rdflib.term.URIRef('foo1')]
>>> cd.roles = 'foo2'
>>> cd.roles
[rdflib.term.URIRef('foo1'), rdflib.term.URIRef('foo2')]
```
To be reverse compatible with SWIG pySBOL, the following pattern should be supported:
```
>>> cd = ComponentDefinition('cd')
>>> cd.roles = 'foo1'
>>> cd.roles
[rdflib.term.URIRef('foo1')]
>>> cd.roles += ['foo2']
WARNING:sbol:Value "foo2 assigned to URIProperty  is of type <class 'str'>. Wrapping it in: <class 'rdflib.term.URIRef'>
>>> cd.roles
[rdflib.term.URIRef('foo1'), rdflib.term.URIRef('foo2')]
```
Ideally, we should support an `append` method as well, but I'm not sure if that's possible

**Comment by tcmitchell** [comment]
The pySBOL version has some odd behavior itself. The `=` operator only sets the first element in the list, rather than overwriting the property's value:

```python
>>> cd = sbol.ComponentDefinition('cd')
>>> cd.roles = 'foo1'
>>> cd.roles 
['foo1']
>>> cd.roles = 'foo2'
>>> cd.roles
['foo2']
>>> cd.roles = ['foo1', 'foo2']
>>> cd.roles
['foo1', 'foo2']

>>> # 'foo2' sticks around, see below
>>> cd.roles = 'foo3'
>>> cd.roles
['foo3', 'foo2']

>>> cd.roles += ['foo4', 'foo5']
>>> cd.roles
['foo3', 'foo2', 'foo4', 'foo5']
>>> 
```

Also note that `append` doesn't appear to do anything in the pysbol version:

```python
>>> cd = sbol.ComponentDefinition('cd')
>>> cd.roles = 'foo1'
>>> cd.roles.append('foo2')
>>> cd.roles
['foo1']
>>> cd.roles.append(['foo2'])
>>> cd.roles
['foo1']
>>> 
```

**Comment by tcmitchell** [comment]
It is not feasible to support the `append` method on URIProperties because the internal value gets converted to a list for consumption by clients. The append method, then, is really `list.append`, and modifies the returned list, which is disconnected from the internal data representation.
