### ISSUE TITLE
Document.read() does not restore roles or object relationships

### ISSUE THREAD

**Issue by tcmitchell** [llotneb/SBOL#3]
When loading the `crispr_example.xml' test file the roles of the component definitions are not associated with the objects. Similarly, the relationships between objects (for example components, functionalComponents, interactions) are not populated.

**Comment by bbartley** [comment]
Last time I checked, round-trip tests reported passing...but this issue suggests that they might in fact be failing and reporting a false-positive

**Comment by tcmitchell** [comment]
This tests are not reporting a false-positive. As discussed in person, because the issue is with the read, the two in-memory documents compare as equal. The information was lost on the first read, into document1. Document1 is then serialized to file and read again as document2. Neither document1 nor document2 have the missing information (roles and relationships).

As discussed earlier, the test is probably insufficient. A comparison should be done between the data in the original file and the data in the newly written file. We may be able to use RDFLib to do that comparison.
