### ISSUE TITLE
Use rdfli.URIRefs internally and externally

### ISSUE THREAD

**Issue by tcmitchell** [llotneb/SBOL#54]
~~Existing code uses defined constants like `sbol.SBO_PRODUCT` to test for membership in a list like Participation.roles. This membership test fails because the participation roles are strings, not URIRefs.~~

~~Make the constants strings instead of URIRefs to match pySBOL and to be backward compatible.~~

Use rdflib.URIRef as the internal representation of URIs, and expose that choice by returning rdflib.URIRefs instead of strings where appropriate. There are many cases, like URIProperty and ReferencedObject, where URIs are stored in data structures. Consistently represent these as rdflib.URIRef and return the URIRef instead of converting it to a Python str.

Note: `rdflib.URIRef` extends type `str`, so we are still returning a string in that sense. What really changes are membership tests.

```Python
>>> import sbol
INFO:rdflib:RDFLib Version: 4.2.2
>>> import rdflib
>>> isinstance(rdflib.URIRef('http://example.com/foo'), str)
True
>>> rdflib.URIRef('http://example.com/foo') in ['http://example.com/foo']
False
>>> 'http://example.com/foo' in [rdflib.URIRef('http://example.com/foo')]
False
```

**Comment by jakebeal** [comment]
Decision on call: committing to URIRefs everywhere we use URIs.
